[sandbox]
scratch_dir = true            # go test, mise run, node-gyp
allow_gpg_signing = true
allow_cache_exec = ["ms-playwright"]
pass_env = ["HOME"]
allow_localhost_any = true

[allow]
read = ["~/Desktop", "~/Library/Application Support/cnctl/config.toml"]

[proxy]
allow_private_domains = ["intern.nav.no", "nav.cloud.nais.io", "prod.nav.cloud.nais.io", "prod-gcp.nav.cloud.nais.io", "dev-gcp.nav.cloud.nais.io", "dev.nav.cloud.nais.io"]

[gh_guard]
enabled = true

[git_guard]
enabled = true
protect_default_branch_only = true
