[env]
DOCKER_HOST = "unix:///Users/hans/.colima/default/docker.sock"
PNPM_HOME = "/Users/hans/Library/pnpm"
NODE_OPTIONS = "--no-deprecation"
FZF_DEFAULT_COMMAND = 'fd --hidden --exclude .git'
KUBECONFIG = "/Users/hans/.kube/config"
KUBE_EDITOR = "nvim"
GOPATH = "/Users/hans/go"
_.path = ["/Users/hans/Library/pnpm"]

[tools]
"aqua:bitwarden/clients" = "cli-v2025.5.0"
fnox = "latest"
gcloud = "528.0.0"
go = "1.26"
opentofu = "latest"
pnpm = "10"
rust = "latest"
uv = "latest"
"go:github.com/sethvargo/ratchet" = "latest"
watchexec = "latest"

[settings]
idiomatic_version_file_enable_tools = []
